### PR TITLE
Modify Passwords Removed 

### PR DESCRIPTION
**Pull request by TTFMF**
I read that the creator of these XDFs vanished from tuning community.  There are many users in the community that wish to continue the work done by the creator of these XDFs, so I removed the modify passwords from them.

### CODE REVIEW

**Comment by DevX-Cipher** [comment]
these still have passwords

**Comment by DevX-Cipher** [comment]
how did you remove them

**Comment by TTFMF** [comment]
> these still have passwords
> 

I just double checked and the ones in my fork do not have passwords.  Which file did you see that still has a password? Maybe I uploaded one with a password by mistake.

**Comment by DevX-Cipher** [comment]
all good do you have a way to remove passwords or

**Comment by TTFMF** [comment]
> how did you remove them

I used a hex editor while running Tuner Pro with the .xdf loaded. The password is in plaintext in a certain area of memory. It's been a while since I did this, so I'd have to look at my notes. I removed the passwords because the owner of the files passed away or disappeared from the tuning community. Leaving progress at a stand still on these .xdf's.

**Comment by DevX-Cipher** [comment]
do you have discord

**Comment by TTFMF** [comment]
> do you have discord
> 

I had one a long time ago, I just created a new one but my account was immediately flagged and disabled without a specific reason given.

**Comment by DevX-Cipher** [comment]
create another lol

**Comment by TTFMF** [comment]
> create another lol
> 

NoBPDU4u#9174

**Pull request merged**
